---
title: Code
---

The following list provides links to the slides and code used in the guided coding sessions. The solutions to the challenges will be made available through RStudio Server.

<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Monday August 6: Efficient data analysis with R.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>
<li><p><a href="slides/01-slides-big-data.pdf">SLIDES: Introduction to the course. Good coding practices in R.</a></p>
</li>

<li><p><a href="code/00-setup.html">Introduction to RMarkdown and Setup</a> (<a href="code/00-setup.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="slides/02-slides-parallel.pdf">SLIDES: Parallel computing</a></p>
</li>

<li><p><a href="code/01-efficient-programming.html">Efficient programming in R</a> (<a href="code/01-efficient-programming.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge1.Rmd">Coding challenge 1: Writing more efficient code (.Rmd file)</a></p>
</li>

<li><p><a href="code/02-parallel-computing.html">Parallel computing in R
</a> (<a href="code/02-parallel-computing.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge2.Rmd">Coding challenge 2: Parallel computing (.Rmd file)</a></p>
</li>


</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse2">Tuesday August 7th: Cloud computing.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>

<li><p><a href="slides/03-slides-SQL.pdf">SLIDES: Introduction to SQL.</a></p>
</li>

<li><p><a href="code/03-sql-intro.html">Querying an SQL database</a> (<a href="code/03-sql-intro.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge3.Rmd">Coding challenge 3 (.Rmd file)</a></p>

<li><p><a href="code/04-sql-advanced.html">Querying multiple SQL tables</a> (<a href="code/04-sql-advanced.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge4.Rmd">Coding challenge 4 (.Rmd file)</a></p>

<li><p><a href="code/05-bigquery-intro.html">Parallel computing in R
</a> (<a href="code/05-bigquery-intro.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/06-bigquery-advanced.html">Querying a massive-scale Google BigQuery database
</a> (<a href="code/06-bigquery-advanced.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge5.Rmd">Coding challenge 5 (.Rmd file)</a></p>
</li>

</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse3">Wednesday August 8th: Large-scale discovery in networks.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>

<li><p><a href="slides/04-slides-networks.pdf">SLIDES: Large-scale discovery in networks.</a></p>
</li>

<li><p><a href="code/07-networks-intro.html">Basics of network analysis</a> (<a href="code/07-networks-intro.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/08-community-detection.html">Community detection in large-scale networks</a> (<a href="code/08-community-detection.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge6.Rmd">Coding challenge 6 (.Rmd file)</a></p>


<li><p><a href="code/09-latent-space.html">Latent space network models
</a> (<a href="code/09-latent-space.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge7.Rmd">Coding challenge 7 (.Rmd file)</a></p>
</li>


</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse4">Thursday August 9th: Text classification at scale.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>

<li><p><a href="slides/05-slides-text-dictionaries.pdf">SLIDES: Text analysis. Dictionary methods.</a></p>
</li>

<li><p><a href="code/10-dictionary-methods.html">Dictionary methods</a> (<a href="code/10-dictionary-methods.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge8.Rmd">Coding challenge 8 (.Rmd file)</a></p>

<li><p><a href="slides/06-slides-text-supervised.pdf">SLIDES: Supervised machine learning methods.</a></p>
</li>

<li><p><a href="code/11-supervised-learning.html">Regularized regression
</a> (<a href="code/11-supervised-learning.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/12-advanced-sml.html">Other classifiers
</a> (<a href="code/12-advanced-sml.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/13-xgboost.html">Xgboost
</a> (<a href="code/13-xgboost.Rmd">.Rmd file</a>)</p>
</li>

<li><p><a href="code/challenge9.Rmd">Coding challenge 9 (.Rmd file)</a></p>
</li>

</ul>
</div>
</div>
</div>


<div class="panel-group">
<div class="panel panel-default">
<div class="panel-heading">
<h2 id="day1" class="panel-title">
<a data-toggle="collapse" href="#collapse5">Friday August 10th: Topic discovery in text.</a>
</h2>
</div>
<div id="collapse1" class="panel-collapse collapse in" style="margin:12px">

<ul>

Coming soon....

</ul>
</div>
</div>
</div>

