---
output:
  html_document:
    toc: true
    toc_depth: 3
---

<div class="container">
<div class="jumbotron" style="margin-left:-15px">
<h1 class="title">Big Data Analysis in the Social Sciences</h1>
<h2 class="subtitle">ECPR Summer School in Methods and Techniques</h2>
<p>Central European University, Budapest, August 6-10 2018</p>
</div>
</div>

Massive-scale datasets from web sources and social media, newly digitized text sources, and large longitudinal survey studies present exciting opportunities for the study of social and political behaviour, but at the same time its size and heterogeneity present significant challenges. This course will introduce participants to new computational methods and tools required to explore and analyse Big Data in the social sciences using the R programming language. It will be structured around techniques to deal with the 3 V's of Big Data: volume, variety, and veracity. First, we will cover the basics of parallel programming, database management, and cloud computing to analyse large-scale datasets. Second, we will learn how to scale human tasks through the use of machine learning methods. Finally, we will discuss how to automatically discover insights from large text and network datasets and validate the output of this analysis. The course will follow a "learning-by-doing" approach, with short theoretical sessions followed by "data challenges" where participants will need to apply new methods.

# Instructors

<table class = "table table-striped">
<tr>
<td><a href="http://www.pablobarbera.com"><strong>Pablo Barberá</strong></a> (Instructor)</td>
<td><a href="mailto:P.Barbera@lse.ac.uk">P.Barbera@lse.ac.uk</a></td>
<td><a href="https://www.twitter.com/p_barbera">@p_barbera</a></td>
</tr>
<tr>
<td><a href="https://tom.paskhal.is/"><strong>Tom Paskhalis</strong></a> (Teaching Assistant)</td>
<td><a href="mailto:t.g.paskhalis@lse.ac.uk">t.g.paskhalis@lse.ac.uk</a></td>
<td><a href="https://www.twitter.com/tpaskhalis">@tpaskhalis</a></td>
</tr>
</table>


# Schedule

<table class = "table table-striped table-hover">
<tr>
<td>Monday August 6, 2018</td>
<td><b>Session 1</b></td>
<td>Good coding practices in R.</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Parallel computing.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Tuesday August 7, 2018</td>
<td><b>Session 1</b></td>
<td>SQL for data manipulation.</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Large-scale data processing in the cloud.</td>
<td> 16:00&ndash;17:30 </td>
</tr>


<td>Wednesday August 8, 2018</td>
<td><b>Session 1</b></td>
<td>Community detection in networks.</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Latent space network models</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Thursday August 9, 2018</td>
<td><b>Session 1</b></td>
<td>Supervised machine learning</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Large-scale text classification.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

<td>Friday August 10, 2018</td>
<td><b>Session 1</b></td>
<td>Exploratory analysis of textual datasets</td>
<td> 14:00&ndash;15:30 </td>
</tr>

<tr>
<td></td>
<td><b>Session 2</b></td>
<td>Topic models.</td>
<td> 16:00&ndash;17:30 </td>
</tr>

</table>


# Prerequisites

The course will assume intermediate familiarity with the R statistical programming language. Participants should be able to know how to read datasets in R, work with vectors and data frames, and run basic statistical analyses, such as linear regression. More advanced knowledge of statistical computing, such as writing functions and loops, is helpful but not required.

Students are expected to bring a laptop to class and follow along the coding section of each session.

# Software 

This course will use [R](https://www.r-project.org/), which is a free and open-source programming language primarily used for statistics and data analysis. We will also use [RStudio](https://www.rstudio.com/), which is an easy-to-use interface to R. 

Installing R or RStudio prior to the workshop is not necessary. The instructor will provide individual login details to an RStudio Server that all workshop participants can access to run their code.

# License and credit

Science should be open, and this course builds up other open licensed material, so unless otherwise noted, all materials for this class are licensed under a <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

The layout for this website was designed by [Jeffrey Arnold](http://www.jrnold.me/) (thanks!).

The source for the materials of this course is on GitHub at <a href="https://github.com/pablobarbera/ECPR-SC105">pablobarbera/ECPR-SC105</a>

# Feedback

If you have any feedback on the course or find any typos or errors in this website go to [issues](https://github.com/pablobarbera/ECPR-SC105/issues), click on the "New Issue" button to create a new issue, and add your suggestion or describe the problem.


